version: '3'

services:
  redis:
    image: redis:3.0.7-alpine
    container_name: redis
    command: redis-server --appendonly yes
  compliance-checker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: compliance-checker-web
    env_file: .env
    volumes:
      - "./contrib/config/config.yml:/usr/lib/ccweb/config.local.yml"
    ports:
      - "3000:3000"
