#!/bin/bash
set -e
wait_for_redis(){
    echo "Waiting for redis"
    until $(redis-cli -h redis ping > /dev/null 2>&1); do 
        printf '.'
        sleep 5
    done
    printf '\n'
}

wait_for_redis
